import { chromium } from 'playwright'
const b = await chromium.launch({ channel: 'chrome' })
const p = await b.newPage({ viewport: { width: 1600, height: 900 } })
p.on('pageerror', (e) => console.log('JS ERROR:', e.message))
await p.goto('http://localhost:5173/', { waitUntil: 'networkidle' })
await p.waitForTimeout(2500)
await p.click('.nav-links a[href="#skills"]')
await p.waitForTimeout(2000)
console.log('fase al llegar por el menú:', await p.evaluate(() => document.querySelector('.skills-panel').dataset.stage))
const cells = p.locator('.badge-cell')
for (const i of [0, 2, 5]) await cells.nth(i).locator('.badge').click()
await p.waitForTimeout(1600)
console.log('descubiertas:', await p.locator('.badge-cell.is-revealed').count(), 'de', await cells.count())
await p.screenshot({ path: 'shots/shoot-after-nav.png' })
await b.close()
